import BaseDictEnum from './baseDictEnum.js';

export const ProductUnitUPS = {
  PIECES: new BaseDictEnum('PIECES', 'productUnit.pieces', 'PCS', 'Pieces'),
  BARREL: new BaseDictEnum('BARREL', 'productUnit.barrel', 'BA', 'Barrel'),
  BUNDLE: new BaseDictEnum('BUNDLE', 'productUnit.bundle', 'BE', 'Bundle'),
  BAG: new BaseDictEnum('BAG', 'productUnit.bag', 'BG', 'Bag'),
  BUNCH: new BaseDictEnum('BUNCH', 'productUnit.bunch', 'BH', 'Bunch'),
  BOX: new BaseDictEnum('BOX', 'productUnit.box', 'BOX', 'Box'),
  BOLT: new BaseDictEnum('BOLT', 'productUnit.bolt', 'BT', 'Bolt'),
  BUTT: new BaseDictEnum('BUTT', 'productUnit.butt', 'BU', 'Butt'),
  CANISTER: new BaseDictEnum(
    'CANISTER',
    'productUnit.canister',
    'CI',
    'Canister',
  ),
  CENTIMETER: new BaseDictEnum(
    'CENTIMETER',
    'productUnit.centimeter',
    'CM',
    'Centimeter',
  ),
  CONTAINER: new BaseDictEnum(
    'CONTAINER',
    'productUnit.container',
    'CON',
    'Container',
  ),
  CRATE: new BaseDictEnum('CRATE', 'productUnit.crate', 'CR', 'Crate'),
  CASE: new BaseDictEnum('CASE', 'productUnit.case', 'CS', 'Case'),
  CARTON: new BaseDictEnum('CARTON', 'productUnit.carton', 'CT', 'Carton'),
  CYLINDER: new BaseDictEnum(
    'CYLINDER',
    'productUnit.cylinder',
    'CY',
    'Cylinder',
  ),
  DOZEN: new BaseDictEnum('DOZEN', 'productUnit.dozen', 'DOZ', 'Dozen'),
  EACH: new BaseDictEnum('EACH', 'productUnit.each', 'EA', 'Each'),
  ENVELOPE: new BaseDictEnum(
    'ENVELOPE',
    'productUnit.envelope',
    'EN',
    'Envelope',
  ),
  FEET: new BaseDictEnum('FEET', 'productUnit.feet', 'FT', 'Feet'),
  KILOGRAM: new BaseDictEnum(
    'KILOGRAM',
    'productUnit.kilogram',
    'KG',
    'Kilogram',
  ),
  KILOGRAMS: new BaseDictEnum(
    'KILOGRAMS',
    'productUnit.kilograms',
    'KGS',
    'Kilograms',
  ),
  POUND: new BaseDictEnum('POUND', 'productUnit.pound', 'LB', 'Pound'),
  POUNDS: new BaseDictEnum('POUNDS', 'productUnit.pounds', 'LBS', 'Pounds'),
  LITER: new BaseDictEnum('LITER', 'productUnit.liter', 'L', 'Liter'),
  METER: new BaseDictEnum('METER', 'productUnit.meter', 'M', 'Meter'),
  NUMBER: new BaseDictEnum('NUMBER', 'productUnit.number', 'NMB', 'Number'),
  PACKET: new BaseDictEnum('PACKET', 'productUnit.packet', 'PA', 'Packet'),
  PALLET: new BaseDictEnum('PALLET', 'productUnit.pallet', 'PAL', 'Pallet'),
  PIECE: new BaseDictEnum('PIECE', 'productUnit.piece', 'PC', 'Piece'),
  PROOF_LITERS: new BaseDictEnum(
    'PROOF_LITERS',
    'productUnit.proofLiters',
    'PF',
    'Proof Liters',
  ),
  PACKAGE: new BaseDictEnum('PACKAGE', 'productUnit.package', 'PKG', 'Package'),
  PAIR: new BaseDictEnum('PAIR', 'productUnit.pair', 'PR', 'Pair'),
  PAIRS: new BaseDictEnum('PAIRS', 'productUnit.pairs', 'PRS', 'Pairs'),
  ROLL: new BaseDictEnum('ROLL', 'productUnit.roll', 'RL', 'Roll'),
  SET: new BaseDictEnum('SET', 'productUnit.set', 'SET', 'Set'),
  SQUARE_METERS: new BaseDictEnum(
    'SQUARE_METERS',
    'productUnit.squareMeters',
    'SME',
    'Square Meters',
  ),
  SQUARE_YARDS: new BaseDictEnum(
    'SQUARE_YARDS',
    'productUnit.squareYards',
    'SYD',
    'Square Yards',
  ),
  TUBE: new BaseDictEnum('TUBE', 'productUnit.tube', 'TU', 'Tube'),
  YARD: new BaseDictEnum('YARD', 'productUnit.yard', 'YD', 'Yard'),
};

export const ProductUnitFedex = {
  PIECES: new BaseDictEnum('PIECES', 'productUnit.pieces', 'PCS', 'Pieces'),
  BARREL: new BaseDictEnum('BARREL', 'productUnit.barrel', 'BA', 'Barrel'),
  BUNDLE: new BaseDictEnum('BUNDLE', 'productUnit.bundle', 'BE', 'Bundle'),
  BAG: new BaseDictEnum('BAG', 'productUnit.bag', 'BG', 'Bag'),
  BUNCH: new BaseDictEnum('BUNCH', 'productUnit.bunch', 'BH', 'Bunch'),

  BOX: new BaseDictEnum('BOX', 'productUnit.box', 'BOX', 'Box'),

  BOLT: new BaseDictEnum('BOLT', 'productUnit.bolt', 'BT', 'Bolt'),

  BUTT: new BaseDictEnum('BUTT', 'productUnit.butt', 'BU', 'Butt'),

  CANISTER: new BaseDictEnum(
    'CANISTER',
    'productUnit.canister',
    'CI',
    'Canister',
  ),
  CENTIMETER: new BaseDictEnum(
    'CENTIMETER',
    'productUnit.centimeter',
    'CM',
    'Centimeter',
  ),
  CONTAINER: new BaseDictEnum(
    'CONTAINER',
    'productUnit.container',
    'CON',
    'Container',
  ),
  CRATE: new BaseDictEnum('CRATE', 'productUnit.crate', 'CR', 'Crate'),
  CASE: new BaseDictEnum('CASE', 'productUnit.case', 'CS', 'Case'),
  CARTON: new BaseDictEnum('CARTON', 'productUnit.carton', 'CT', 'Carton'),
  CYLINDER: new BaseDictEnum(
    'CYLINDER',
    'productUnit.cylinder',
    'CY',
    'Cylinder',
  ),
  DOZEN: new BaseDictEnum('DOZEN', 'productUnit.dozen', 'DOZ', 'Dozen'),
  EACH: new BaseDictEnum('EACH', 'productUnit.each', 'EA', 'Each'),
  ENVELOPE: new BaseDictEnum(
    'ENVELOPE',
    'productUnit.envelope',
    'EN',
    'Envelope',
  ),
  FEET: new BaseDictEnum('FEET', 'productUnit.feet', 'FT', 'Feet'),
  KILOGRAM: new BaseDictEnum(
    'KILOGRAM',
    'productUnit.kilogram',
    'KG',
    'Kilogram',
  ),
  KILOGRAMS: new BaseDictEnum(
    'KILOGRAMS',
    'productUnit.kilograms',
    'KGS',
    'Kilograms',
  ),
  POUND: new BaseDictEnum('POUND', 'productUnit.pound', 'LB', 'Pound'),
  POUNDS: new BaseDictEnum('POUNDS', 'productUnit.pounds', 'LBS', 'Pounds'),
  LITER: new BaseDictEnum('LITER', 'productUnit.liter', 'L', 'Liter'),
  METER: new BaseDictEnum('METER', 'productUnit.meter', 'M', 'Meter'),
  NUMBER: new BaseDictEnum('NUMBER', 'productUnit.number', 'NMB', 'Number'),
  PACKET: new BaseDictEnum('PACKET', 'productUnit.packet', 'PA', 'Packet'),
  PALLET: new BaseDictEnum('PALLET', 'productUnit.pallet', 'PAL', 'Pallet'),
  PIECE: new BaseDictEnum('PIECE', 'productUnit.piece', 'PC', 'Piece'),
  PROOF_LITERS: new BaseDictEnum(
    'PROOF_LITERS',
    'productUnit.proofLiters',
    'PF',
    'Proof Liters',
  ),
  PACKAGE: new BaseDictEnum('PACKAGE', 'productUnit.package', 'PKG', 'Package'),
  PAIR: new BaseDictEnum('PAIR', 'productUnit.pair', 'PR', 'Pair'),
  PAIRS: new BaseDictEnum('PAIRS', 'productUnit.pairs', 'PRS', 'Pairs'),
  ROLL: new BaseDictEnum('ROLL', 'productUnit.roll', 'RL', 'Roll'),
  SET: new BaseDictEnum('SET', 'productUnit.set', 'SET', 'Set'),
  SQUARE_METERS: new BaseDictEnum(
    'SQUARE_METERS',
    'productUnit.squareMeters',
    'SME',
    'Square Meters',
  ),
  SQUARE_YARDS: new BaseDictEnum(
    'SQUARE_YARDS',
    'productUnit.squareYards',
    'SYD',
    'Square Yards',
  ),
  TUBE: new BaseDictEnum('TUBE', 'productUnit.tube', 'TU', 'Tube'),
  YARD: new BaseDictEnum('YARD', 'productUnit.yard', 'YD', 'Yard'),
};

export const ProductUnitDHL = {
  PIECES: new BaseDictEnum('PIECES', 'productUnit.pieces', 'PCS', 'Pieces'),
  BOXES: new BaseDictEnum('BOXES', 'productUnit.boxes', 'BOX', 'Boxes'),
  CENTIGRAM: new BaseDictEnum(
    'CENTIGRAM',
    'productUnit.centigram',
    '2GM',
    'Centigram',
  ),
  CENTIMETERS: new BaseDictEnum(
    'CENTIMETERS',
    'productUnit.centimeters',
    '2M',
    'Centimeters',
  ),
  CUBIC_CENTIMETERS: new BaseDictEnum(
    'CUBIC_CENTIMETERS',
    'productUnit.cubicCentimeters',
    '2M3',
    'Cubic Centimeters',
  ),
  CUBIC_FEET: new BaseDictEnum(
    'CUBIC_FEET',
    'productUnit.cubicFeet',
    '3M3',
    'Cubic Feet',
  ),
  CUBIC_METERS: new BaseDictEnum(
    'CUBIC_METERS',
    'productUnit.cubicMeters',
    'M3',
    'Cubic Meters',
  ),
  DOZEN_PAIRS: new BaseDictEnum(
    'DOZEN_PAIRS',
    'productUnit.dozenPairs',
    'DPR',
    'Dozen Pairs',
  ),
  DOZEN: new BaseDictEnum('DOZEN', 'productUnit.dozen', 'DOZ', 'Dozen'),
  EACH: new BaseDictEnum('EACH', 'productUnit.each', 'NO', 'Each'),
  GRAMS: new BaseDictEnum('GRAMS', 'productUnit.grams', 'GM', 'Grams'),
  GROSS: new BaseDictEnum('GROSS', 'productUnit.gross', 'GRS', 'Gross'),
  KILOGRAMS: new BaseDictEnum(
    'KILOGRAMS',
    'productUnit.kilograms',
    'KG',
    'Kilograms',
  ),
  LITERS: new BaseDictEnum('LITERS', 'productUnit.liters', 'L', 'Liters'),
  METERS: new BaseDictEnum('METERS', 'productUnit.meters', 'M', 'Meters'),
  MILLIGRAMS: new BaseDictEnum(
    'MILLIGRAMS',
    'productUnit.milligrams',
    '3GM',
    'Milligrams',
  ),
  MILLILITERS: new BaseDictEnum(
    'MILLILITERS',
    'productUnit.milliliters',
    '3L',
    'Milliliters',
  ),
  NO_UNIT_REQUIRED: new BaseDictEnum(
    'NO_UNIT_REQUIRED',
    'productUnit.noUnitRequired',
    'X',
    'No Unit Required',
  ),
  NUMBER: new BaseDictEnum('NUMBER', 'productUnit.number', 'NO', 'Number'),
  OUNCES: new BaseDictEnum('OUNCES', 'productUnit.ounces', '2KG', 'Ounces'),
  PAIRS: new BaseDictEnum('PAIRS', 'productUnit.pairs', 'PRS', 'Pairs'),
  GALLONS: new BaseDictEnum('GALLONS', 'productUnit.gallons', '2L', 'Gallons'),
  POUNDS: new BaseDictEnum('POUNDS', 'productUnit.pounds', '3KG', 'Pounds'),
  SQUARE_CENTIMETERS: new BaseDictEnum(
    'SQUARE_CENTIMETERS',
    'productUnit.squareCentimeters',
    'CM2',
    'Square Centimeters',
  ),
  SQUARE_FEET: new BaseDictEnum(
    'SQUARE_FEET',
    'productUnit.squareFeet',
    '2M2',
    'Square Feet',
  ),
  SQUARE_INCHES: new BaseDictEnum(
    'SQUARE_INCHES',
    'productUnit.squareInches',
    '3M2',
    'Square Inches',
  ),
  SQUARE_METERS: new BaseDictEnum(
    'SQUARE_METERS',
    'productUnit.squareMeters',
    'M2',
    'Square Meters',
  ),
  SQUARE_YARDS: new BaseDictEnum(
    'SQUARE_YARDS',
    'productUnit.squareYards',
    '4M2',
    'Square Yards',
  ),
  YARDS: new BaseDictEnum('YARDS', 'productUnit.yards', '3M', 'Yards'),
};
