export default {
  base: '/api',
  dicts: {
    base: '/dicts',
    get: '/getDicts',
  },
  users: {
    base: '/users',
    signUp: '/signUp',
    signIn: '/signIn',
    getUserInfo: '/getUserInfo',
    refreshToken: '/refreshToken',
  },
  verykGeneral: {
    base: '/veryk/general',
    getCarriers: '/getCarriers',
    getProvinces: '/getProvinces',
    getRegions: '/getRegions',
  },
  verykShipment: {
    base: '/veryk/shipment',
    getAvailableCarriers: '/getAvailableCarriers',
    quote: '/quote',
    save: '/save',
    submit: '/submit',
    get: '/get/:number',
    delete: '/delete/:number',
    getDetail: '/getDetail/:number',
    page: '/page',
    shipmentList: '/shipmentList',
    shipmentDetail: '/shipmentDetail/:id',
    getSignedLabelUrl: '/getSignedLabelUrl',
    tracking: '/tracking',
  },
};
