export const regions = [
  {
    id: 'AD',
    name: 'Andorra',
    type: 'CP',
    timezone: 'Europe/Andorra',
    timezones: ['Europe/Andorra'],
    languages: ['ca'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '376',
  },
  {
    id: 'AF',
    name: 'Afghanistan',
    type: 'C',
    timezone: 'Asia/Kabul',
    timezones: ['Asia/Kabul'],
    languages: ['fa', 'ps'],
    currency: {
      code: 'AFN',
      symbol: 'Af',
      value: '0.00',
    },
    phoneCode: '93',
  },
  {
    id: 'AG',
    name: 'Antigua and Barbuda',
    type: 'C',
    timezone: 'America/Antigua',
    timezones: ['America/Antigua'],
    languages: ['en'],
    currency: {
      code: 'XCD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'AI',
    name: 'Anguilla',
    type: 'S',
    timezone: 'America/Anguilla',
    timezones: ['America/Anguilla'],
    languages: ['en'],
    currency: {
      code: 'XCD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'AL',
    name: 'Albania',
    type: 'C',
    timezone: 'Europe/Tirane',
    timezones: ['Europe/Tirane'],
    languages: ['sq'],
    currency: {
      code: 'ALL',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '355',
  },
  {
    id: 'AM',
    name: 'Armenia',
    type: 'CP',
    timezone: 'Asia/Yerevan',
    timezones: ['Asia/Yerevan'],
    languages: ['hy'],
    currency: {
      code: 'AMD',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '374',
  },
  {
    id: 'AO',
    name: 'Angola',
    type: 'C',
    timezone: 'Africa/Luanda',
    timezones: ['Africa/Luanda'],
    languages: ['kmb', 'pt', 'umb'],
    currency: {
      code: 'AOA',
      symbol: 'Kz',
      value: '0.00',
    },
    phoneCode: '244',
  },
  {
    id: 'AQ',
    name: 'Antarctica',
    type: '',
    timezone: 'Antarctica/Casey',
    timezones: [
      'Antarctica/Casey',
      'Antarctica/Davis',
      'Antarctica/DumontDUrville',
      'Antarctica/Mawson',
      'Antarctica/McMurdo',
      'Antarctica/Palmer',
      'Antarctica/Rothera',
      'Antarctica/South_Pole',
      'Antarctica/Syowa',
      'Antarctica/Vostok',
    ],
    languages: ['und'],
    currency: {
      code: 'XXX',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '672',
  },
  {
    id: 'AR',
    name: 'Argentina',
    type: 'CP',
    timezone: 'America/Argentina/La_Rioja',
    timezones: [
      'America/Argentina/La_Rioja',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Salta',
      'America/Argentina/San_Juan',
      'America/Argentina/San_Luis',
      'America/Argentina/Tucuman',
      'America/Argentina/Ushuaia',
      'America/Buenos_Aires',
      'America/Catamarca',
      'America/Cordoba',
      'America/Jujuy',
      'America/Mendoza',
    ],
    languages: ['es'],
    currency: {
      code: 'ARS',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '54',
  },
  {
    id: 'AS',
    name: 'American Samoa',
    type: 'CP',
    timezone: 'Pacific/Pago_Pago',
    timezones: ['Pacific/Pago_Pago'],
    languages: ['en', 'sm'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'AT',
    name: 'Austria',
    type: 'CP',
    timezone: 'Europe/Vienna',
    timezones: ['Europe/Vienna'],
    languages: ['de'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '43',
  },
  {
    id: 'AU',
    name: 'Australia',
    type: 'CP',
    timezone: 'Australia/Adelaide',
    timezones: [
      'Australia/Adelaide',
      'Australia/Brisbane',
      'Australia/Broken_Hill',
      'Australia/Currie',
      'Australia/Darwin',
      'Australia/Eucla',
      'Australia/Hobart',
      'Australia/Lindeman',
      'Australia/Lord_Howe',
      'Australia/Melbourne',
      'Australia/Perth',
      'Australia/Sydney',
    ],
    languages: ['en'],
    currency: {
      code: 'AUD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '61',
  },
  {
    id: 'AW',
    name: 'Aruba',
    type: 'C',
    timezone: 'America/Aruba',
    timezones: ['America/Aruba'],
    languages: ['nl'],
    currency: {
      code: 'AWG',
      symbol: 'Afl.',
      value: '0.00',
    },
    phoneCode: '297',
  },
  {
    id: 'AZ',
    name: 'Azerbaijan',
    type: 'CP',
    timezone: 'Asia/Baku',
    timezones: ['Asia/Baku'],
    languages: ['az'],
    currency: {
      code: 'AZN',
      symbol: 'man.',
      value: '0.00',
    },
    phoneCode: '994',
  },
  {
    id: 'DZ',
    name: 'Algeria',
    type: 'CP',
    timezone: 'Africa/Algiers',
    timezones: ['Africa/Algiers'],
    languages: ['ar', 'fr', 'kab'],
    currency: {
      code: 'DZD',
      symbol: 'DA',
      value: '0.00',
    },
    phoneCode: '213',
  },
  {
    id: 'BA',
    name: 'Bosnia and Herzegovina',
    type: 'CP',
    timezone: 'Europe/Sarajevo',
    timezones: ['Europe/Sarajevo'],
    languages: ['bs', 'hr', 'sr'],
    currency: {
      code: 'BAM',
      symbol: 'KM',
      value: '0.00',
    },
    phoneCode: '387',
  },
  {
    id: 'BB',
    name: 'Barbados',
    type: 'C',
    timezone: 'America/Barbados',
    timezones: ['America/Barbados'],
    languages: ['en'],
    currency: {
      code: 'BBD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'BD',
    name: 'Bangladesh',
    type: 'CP',
    timezone: 'Asia/Dhaka',
    timezones: ['Asia/Dhaka'],
    languages: ['bn'],
    currency: {
      code: 'BDT',
      symbol: 'Tk',
      value: '0.00',
    },
    phoneCode: '880',
  },
  {
    id: 'BE',
    name: 'Belgium',
    type: 'CP',
    timezone: 'Europe/Brussels',
    timezones: ['Europe/Brussels'],
    languages: ['de', 'fr', 'nl'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '32',
  },
  {
    id: 'BF',
    name: 'Burkina Faso',
    type: 'C',
    timezone: 'Africa/Ouagadougou',
    timezones: ['Africa/Ouagadougou'],
    languages: ['dyu', 'fr', 'mos'],
    currency: {
      code: 'XOF',
      symbol: 'CFA',
      value: '0.00',
    },
    phoneCode: '226',
  },
  {
    id: 'BG',
    name: 'Bulgaria',
    type: 'CP',
    timezone: 'Europe/Sofia',
    timezones: ['Europe/Sofia'],
    languages: ['bg'],
    currency: {
      code: 'BGN',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '359',
  },
  {
    id: 'BH',
    name: 'Bahrain',
    type: 'C',
    timezone: 'Asia/Bahrain',
    timezones: ['Asia/Bahrain'],
    languages: ['ar'],
    currency: {
      code: 'BHD',
      symbol: 'BD',
      value: '0.00',
    },
    phoneCode: '973',
  },
  {
    id: 'BI',
    name: 'Burundi',
    type: 'C',
    timezone: 'Africa/Bujumbura',
    timezones: ['Africa/Bujumbura'],
    languages: ['fr', 'rn'],
    currency: {
      code: 'BIF',
      symbol: 'FBu',
      value: '0.00',
    },
    phoneCode: '257',
  },
  {
    id: 'BJ',
    name: 'Benin',
    type: 'C',
    timezone: 'Africa/Porto-Novo',
    timezones: ['Africa/Porto-Novo'],
    languages: ['fon', 'fr'],
    currency: {
      code: 'XOF',
      symbol: 'CFA',
      value: '0.00',
    },
    phoneCode: '229',
  },
  {
    id: 'BM',
    name: 'Bermuda',
    type: 'C',
    timezone: 'Atlantic/Bermuda',
    timezones: ['Atlantic/Bermuda'],
    languages: ['en'],
    currency: {
      code: 'BMD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'BN',
    name: 'Brunei',
    type: 'CP',
    timezone: 'Asia/Brunei',
    timezones: ['Asia/Brunei'],
    languages: ['ms'],
    currency: {
      code: 'BND',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '673',
  },
  {
    id: 'BO',
    name: 'Bolivia',
    type: 'C',
    timezone: 'America/La_Paz',
    timezones: ['America/La_Paz'],
    languages: ['ay', 'es', 'qu'],
    currency: {
      code: 'BOB',
      symbol: 'Bs',
      value: '0.00',
    },
    phoneCode: '591',
  },
  {
    id: 'BQ',
    name: 'British Antarctic Territory',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'BR',
    name: 'Brazil',
    type: 'CP',
    timezone: 'America/Araguaina',
    timezones: [
      'America/Araguaina',
      'America/Bahia',
      'America/Belem',
      'America/Boa_Vista',
      'America/Campo_Grande',
      'America/Cuiaba',
      'America/Eirunepe',
      'America/Fortaleza',
      'America/Maceio',
      'America/Manaus',
      'America/Noronha',
      'America/Porto_Velho',
      'America/Recife',
      'America/Rio_Branco',
      'America/Santarem',
      'America/Sao_Paulo',
    ],
    languages: ['pt'],
    currency: {
      code: 'BRL',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '55',
  },
  {
    id: 'BS',
    name: 'Bahamas',
    type: 'C',
    timezone: 'America/Nassau',
    timezones: ['America/Nassau'],
    languages: ['en'],
    currency: {
      code: 'BSD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'BT',
    name: 'Bhutan',
    type: 'C',
    timezone: 'Asia/Thimphu',
    timezones: ['Asia/Thimphu'],
    languages: ['dz'],
    currency: {
      code: 'BTN',
      symbol: 'Nu.',
      value: '0.00',
    },
    phoneCode: '975',
  },
  {
    id: 'BV',
    name: 'Bouvet Island',
    type: '',
    timezone: null,
    timezones: [],
    languages: ['und'],
    currency: {
      code: 'NOK',
      symbol: 'Nkr',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'BW',
    name: 'Botswana',
    type: 'C',
    timezone: 'Africa/Gaborone',
    timezones: ['Africa/Gaborone'],
    languages: ['en', 'tn'],
    currency: {
      code: 'BWP',
      symbol: 'BWP',
      value: '0.00',
    },
    phoneCode: '267',
  },
  {
    id: 'BY',
    name: 'Belarus',
    type: 'CP',
    timezone: 'Europe/Minsk',
    timezones: ['Europe/Minsk'],
    languages: ['be', 'ru'],
    currency: {
      code: 'BYR',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '375',
  },
  {
    id: 'BZ',
    name: 'Belize',
    type: 'C',
    timezone: 'America/Belize',
    timezones: ['America/Belize'],
    languages: ['en'],
    currency: {
      code: 'BZD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '501',
  },
  {
    id: 'IO',
    name: 'British Indian Ocean Territory',
    type: '',
    timezone: 'Indian/Chagos',
    timezones: ['Indian/Chagos'],
    languages: ['und'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '246',
  },
  {
    id: 'VG',
    name: 'British Virgin Islands',
    type: 'C',
    timezone: 'America/Tortola',
    timezones: ['America/Tortola'],
    languages: ['en'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'CA',
    name: 'Canada',
    type: 'CP',
    timezone: 'America/Blanc-Sablon',
    timezones: [
      'America/Blanc-Sablon',
      'America/Cambridge_Bay',
      'America/Coral_Harbour',
      'America/Dawson',
      'America/Dawson_Creek',
      'America/Edmonton',
      'America/Glace_Bay',
      'America/Goose_Bay',
      'America/Halifax',
      'America/Inuvik',
      'America/Iqaluit',
      'America/Moncton',
      'America/Montreal',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Rainy_River',
      'America/Rankin_Inlet',
      'America/Regina',
      'America/Resolute',
      'America/St_Johns',
      'America/Swift_Current',
      'America/Thunder_Bay',
      'America/Toronto',
      'America/Vancouver',
      'America/Whitehorse',
      'America/Winnipeg',
      'America/Yellowknife',
    ],
    languages: ['en', 'fr', 'iu'],
    currency: {
      code: 'CAD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'CC',
    name: 'Cocos [Keeling] Islands',
    type: '',
    timezone: 'Indian/Cocos',
    timezones: ['Indian/Cocos'],
    languages: ['en'],
    currency: {
      code: 'AUD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '61',
  },
  {
    id: 'CD',
    name: 'Congo - Kinshasa',
    type: 'C',
    timezone: 'Africa/Kinshasa',
    timezones: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
    languages: ['fr', 'kg', 'ln', 'lu', 'lua'],
    currency: {
      code: 'CDF',
      symbol: 'CDF',
      value: '0.00',
    },
    phoneCode: '243',
  },
  {
    id: 'CF',
    name: 'Central African Republic',
    type: 'C',
    timezone: 'Africa/Bangui',
    timezones: ['Africa/Bangui'],
    languages: ['fr', 'sg'],
    currency: {
      code: 'XAF',
      symbol: 'FCFA',
      value: '0.00',
    },
    phoneCode: '236',
  },
  {
    id: 'CG',
    name: 'Congo - Brazzaville',
    type: 'C',
    timezone: 'Africa/Brazzaville',
    timezones: ['Africa/Brazzaville'],
    languages: ['fr', 'ln'],
    currency: {
      code: 'XAF',
      symbol: 'FCFA',
      value: '0.00',
    },
    phoneCode: '242',
  },
  {
    id: 'CI',
    name: 'Côte d’Ivoire',
    type: 'C',
    timezone: 'Africa/Abidjan',
    timezones: ['Africa/Abidjan'],
    languages: ['fr'],
    currency: {
      code: 'XOF',
      symbol: 'CFA',
      value: '0.00',
    },
    phoneCode: '225',
  },
  {
    id: 'CK',
    name: 'Cook Islands',
    type: 'C',
    timezone: 'Pacific/Rarotonga',
    timezones: ['Pacific/Rarotonga'],
    languages: ['en'],
    currency: {
      code: 'NZD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '682',
  },
  {
    id: 'CL',
    name: 'Chile',
    type: 'C',
    timezone: 'America/Santiago',
    timezones: ['America/Santiago', 'Pacific/Easter'],
    languages: ['es'],
    currency: {
      code: 'CLP',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '56',
  },
  {
    id: 'CM',
    name: 'Cameroon',
    type: 'C',
    timezone: 'Africa/Douala',
    timezones: ['Africa/Douala'],
    languages: ['en', 'fr'],
    currency: {
      code: 'XAF',
      symbol: 'FCFA',
      value: '0.00',
    },
    phoneCode: '237',
  },
  {
    id: 'CN',
    name: 'China',
    type: 'CP',
    timezone: 'Asia/Chongqing',
    timezones: [
      'Asia/Chongqing',
      'Asia/Harbin',
      'Asia/Kashgar',
      'Asia/Shanghai',
      'Asia/Urumqi',
    ],
    languages: ['bo', 'ii', 'ug', 'za', 'zh'],
    currency: {
      code: 'CNY',
      symbol: 'CN¥',
      value: '0.00',
    },
    phoneCode: '86',
  },
  {
    id: 'CO',
    name: 'Colombia',
    type: 'CP',
    timezone: 'America/Bogota',
    timezones: ['America/Bogota'],
    languages: ['es'],
    currency: {
      code: 'COP',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '57',
  },
  {
    id: 'CR',
    name: 'Costa Rica',
    type: 'C',
    timezone: 'America/Costa_Rica',
    timezones: ['America/Costa_Rica'],
    languages: ['es'],
    currency: {
      code: 'CRC',
      symbol: '₡',
      value: '0.00',
    },
    phoneCode: '506',
  },
  {
    id: 'CT',
    name: 'Canton and Enderbury Islands',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'CU',
    name: 'Cuba',
    type: 'CP',
    timezone: 'America/Havana',
    timezones: ['America/Havana'],
    languages: ['es'],
    currency: {
      code: 'CUC',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '53',
  },
  {
    id: 'CV',
    name: 'Cape Verde',
    type: 'C',
    timezone: 'Atlantic/Cape_Verde',
    timezones: ['Atlantic/Cape_Verde'],
    languages: ['pt'],
    currency: {
      code: 'CVE',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '238',
  },
  {
    id: 'CX',
    name: 'Christmas Island',
    type: '',
    timezone: 'Indian/Christmas',
    timezones: ['Indian/Christmas'],
    languages: ['en'],
    currency: {
      code: 'AUD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '61',
  },
  {
    id: 'CY',
    name: 'Cyprus',
    type: 'CP',
    timezone: 'Asia/Nicosia',
    timezones: ['Asia/Nicosia'],
    languages: ['el', 'tr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '357',
  },
  {
    id: 'CZ',
    name: 'Czech Republic',
    type: 'CP',
    timezone: 'Europe/Prague',
    timezones: ['Europe/Prague'],
    languages: ['cs'],
    currency: {
      code: 'CZK',
      symbol: 'Kč',
      value: '0.00',
    },
    phoneCode: '420',
  },
  {
    id: 'HR',
    name: 'Croatia',
    type: 'CP',
    timezone: 'Europe/Zagreb',
    timezones: ['Europe/Zagreb'],
    languages: ['hr'],
    currency: {
      code: 'HRK',
      symbol: 'kn',
      value: '0.00',
    },
    phoneCode: '385',
  },
  {
    id: 'KH',
    name: 'Cambodia',
    type: 'C',
    timezone: 'Asia/Phnom_Penh',
    timezones: ['Asia/Phnom_Penh'],
    languages: ['km'],
    currency: {
      code: 'KHR',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '855',
  },
  {
    id: 'KM',
    name: 'Comoros',
    type: 'C',
    timezone: 'Indian/Comoro',
    timezones: ['Indian/Comoro'],
    languages: ['ar', 'fr'],
    currency: {
      code: 'KMF',
      symbol: 'CF',
      value: '0.00',
    },
    phoneCode: '269',
  },
  {
    id: 'KY',
    name: 'Cayman Islands',
    type: 'C',
    timezone: 'America/Cayman',
    timezones: ['America/Cayman'],
    languages: ['en'],
    currency: {
      code: 'KYD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'TD',
    name: 'Chad',
    type: 'C',
    timezone: 'Africa/Ndjamena',
    timezones: ['Africa/Ndjamena'],
    languages: ['ar', 'fr'],
    currency: {
      code: 'XAF',
      symbol: 'FCFA',
      value: '0.00',
    },
    phoneCode: '235',
  },
  {
    id: 'DJ',
    name: 'Djibouti',
    type: 'C',
    timezone: 'Africa/Djibouti',
    timezones: ['Africa/Djibouti'],
    languages: ['aa', 'ar', 'fr'],
    currency: {
      code: 'DJF',
      symbol: 'Fdj',
      value: '0.00',
    },
    phoneCode: '253',
  },
  {
    id: 'DK',
    name: 'Denmark',
    type: 'CP',
    timezone: 'Europe/Copenhagen',
    timezones: ['Europe/Copenhagen'],
    languages: ['da'],
    currency: {
      code: 'DKK',
      symbol: 'Dkr',
      value: '0.00',
    },
    phoneCode: '45',
  },
  {
    id: 'DM',
    name: 'Dominica',
    type: 'C',
    timezone: 'America/Dominica',
    timezones: ['America/Dominica'],
    languages: ['en'],
    currency: {
      code: 'XCD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'DO',
    name: 'Dominican Republic',
    type: 'C',
    timezone: 'America/Santo_Domingo',
    timezones: ['America/Santo_Domingo'],
    languages: ['es'],
    currency: {
      code: 'DOP',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'NQ',
    name: 'Dronning Maud Land',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'DD',
    name: 'East Germany',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: 'DDM',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'EC',
    name: 'Ecuador',
    type: 'CP',
    timezone: 'America/Guayaquil',
    timezones: ['America/Guayaquil', 'Pacific/Galapagos'],
    languages: ['es'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '593',
  },
  {
    id: 'EE',
    name: 'Estonia',
    type: 'CP',
    timezone: 'Europe/Tallinn',
    timezones: ['Europe/Tallinn'],
    languages: ['et'],
    currency: {
      code: 'EEK',
      symbol: 'Ekr',
      value: '0.00',
    },
    phoneCode: '372',
  },
  {
    id: 'EG',
    name: 'Egypt',
    type: 'C',
    timezone: 'Africa/Cairo',
    timezones: ['Africa/Cairo'],
    languages: ['ar'],
    currency: {
      code: 'EGP',
      symbol: 'EG£',
      value: '0.00',
    },
    phoneCode: '20',
  },
  {
    id: 'ER',
    name: 'Eritrea',
    type: 'C',
    timezone: 'Africa/Asmera',
    timezones: ['Africa/Asmera'],
    languages: ['ar', 'ti', 'tig'],
    currency: {
      code: 'ERN',
      symbol: 'Nfk',
      value: '0.00',
    },
    phoneCode: '291',
  },
  {
    id: 'ET',
    name: 'Ethiopia',
    type: 'CP',
    timezone: 'Africa/Addis_Ababa',
    timezones: ['Africa/Addis_Ababa'],
    languages: ['aa', 'am', 'om', 'sid', 'wal'],
    currency: {
      code: 'ETB',
      symbol: 'Br',
      value: '0.00',
    },
    phoneCode: '251',
  },
  {
    id: 'GQ',
    name: 'Equatorial Guinea',
    type: 'C',
    timezone: 'Africa/Malabo',
    timezones: ['Africa/Malabo'],
    languages: ['es', 'fan', 'fr'],
    currency: {
      code: 'XAF',
      symbol: 'FCFA',
      value: '0.00',
    },
    phoneCode: '240',
  },
  {
    id: 'SV',
    name: 'El Salvador',
    type: 'C',
    timezone: 'America/El_Salvador',
    timezones: ['America/El_Salvador'],
    languages: ['es'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '503',
  },
  {
    id: 'FI',
    name: 'Finland',
    type: 'P',
    timezone: 'Europe/Helsinki',
    timezones: ['Europe/Helsinki'],
    languages: ['fi', 'sv'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '358',
  },
  {
    id: 'FJ',
    name: 'Fiji',
    type: 'C',
    timezone: 'Pacific/Fiji',
    timezones: ['Pacific/Fiji'],
    languages: ['en', 'fj'],
    currency: {
      code: 'FJD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '679',
  },
  {
    id: 'FK',
    name: 'Falkland Islands',
    type: 'C',
    timezone: 'Atlantic/Stanley',
    timezones: ['Atlantic/Stanley'],
    languages: ['en'],
    currency: {
      code: 'FKP',
      symbol: 'FK£',
      value: '0.00',
    },
    phoneCode: '500',
  },
  {
    id: 'FO',
    name: 'Faroe Islands',
    type: 'CP',
    timezone: 'Atlantic/Faeroe',
    timezones: ['Atlantic/Faeroe'],
    languages: ['fo'],
    currency: {
      code: 'DKK',
      symbol: 'Dkr',
      value: '0.00',
    },
    phoneCode: '298',
  },
  {
    id: 'FQ',
    name: 'French Southern and Antarctic Territories',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'FR',
    name: 'France',
    type: 'CP',
    timezone: 'Europe/Paris',
    timezones: ['Europe/Paris'],
    languages: ['fr', 'oc'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '33',
  },
  {
    id: 'GF',
    name: 'French Guiana',
    type: 'CP',
    timezone: 'America/Cayenne',
    timezones: ['America/Cayenne'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '594',
  },
  {
    id: 'PF',
    name: 'French Polynesia',
    type: 'C',
    timezone: 'Pacific/Gambier',
    timezones: ['Pacific/Gambier', 'Pacific/Marquesas', 'Pacific/Tahiti'],
    languages: ['fr', 'ty'],
    currency: {
      code: 'XPF',
      symbol: 'CFPF',
      value: '0.00',
    },
    phoneCode: '689',
  },
  {
    id: 'TF',
    name: 'French Southern Territories',
    type: '',
    timezone: 'Indian/Kerguelen',
    timezones: ['Indian/Kerguelen'],
    languages: ['und'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '262',
  },
  {
    id: 'DE',
    name: 'Germany',
    type: 'CP',
    timezone: 'Europe/Berlin',
    timezones: ['Europe/Berlin'],
    languages: ['de'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '49',
  },
  {
    id: 'GA',
    name: 'Gabon',
    type: 'C',
    timezone: 'Africa/Libreville',
    timezones: ['Africa/Libreville'],
    languages: ['fr'],
    currency: {
      code: 'XAF',
      symbol: 'FCFA',
      value: '0.00',
    },
    phoneCode: '241',
  },
  {
    id: 'GD',
    name: 'Grenada',
    type: 'C',
    timezone: 'America/Grenada',
    timezones: ['America/Grenada'],
    languages: ['en'],
    currency: {
      code: 'XCD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'GE',
    name: 'Georgia',
    type: 'CP',
    timezone: 'Asia/Tbilisi',
    timezones: ['Asia/Tbilisi'],
    languages: ['ab', 'ka', 'os'],
    currency: {
      code: 'GEL',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '995',
  },
  {
    id: 'GG',
    name: 'Guernsey',
    type: 'CP',
    timezone: 'Europe/Guernsey',
    timezones: ['Europe/Guernsey'],
    languages: ['en'],
    currency: {
      code: 'GBP',
      symbol: '£',
      value: '0.00',
    },
    phoneCode: '44',
  },
  {
    id: 'GH',
    name: 'Ghana',
    type: 'C',
    timezone: 'Africa/Accra',
    timezones: ['Africa/Accra'],
    languages: ['ak', 'ee', 'en', 'gaa', 'tw'],
    currency: {
      code: 'GHS',
      symbol: 'GH₵',
      value: '0.00',
    },
    phoneCode: '233',
  },
  {
    id: 'GI',
    name: 'Gibraltar',
    type: 'C',
    timezone: 'Europe/Gibraltar',
    timezones: ['Europe/Gibraltar'],
    languages: ['en'],
    currency: {
      code: 'GIP',
      symbol: 'GI£',
      value: '0.00',
    },
    phoneCode: '350',
  },
  {
    id: 'GL',
    name: 'Greenland',
    type: 'CP',
    timezone: 'America/Danmarkshavn',
    timezones: [
      'America/Danmarkshavn',
      'America/Godthab',
      'America/Scoresbysund',
      'America/Thule',
    ],
    languages: ['da', 'iu', 'kl'],
    currency: {
      code: 'DKK',
      symbol: 'Dkr',
      value: '0.00',
    },
    phoneCode: '299',
  },
  {
    id: 'GM',
    name: 'Gambia',
    type: 'C',
    timezone: 'Africa/Banjul',
    timezones: ['Africa/Banjul'],
    languages: ['en'],
    currency: {
      code: 'GMD',
      symbol: 'GMD',
      value: '0.00',
    },
    phoneCode: '220',
  },
  {
    id: 'GN',
    name: 'Guinea',
    type: 'C',
    timezone: 'Africa/Conakry',
    timezones: ['Africa/Conakry'],
    languages: ['fr', 'sus'],
    currency: {
      code: 'GNF',
      symbol: 'FG',
      value: '0.00',
    },
    phoneCode: '224',
  },
  {
    id: 'GP',
    name: 'Guadeloupe',
    type: 'CP',
    timezone: 'America/Guadeloupe',
    timezones: ['America/Guadeloupe'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '590',
  },
  {
    id: 'GR',
    name: 'Greece',
    type: 'CP',
    timezone: 'Europe/Athens',
    timezones: ['Europe/Athens'],
    languages: ['el'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '30',
  },
  {
    id: 'GT',
    name: 'Guatemala',
    type: 'C',
    timezone: 'America/Guatemala',
    timezones: ['America/Guatemala'],
    languages: ['es'],
    currency: {
      code: 'GTQ',
      symbol: 'GTQ',
      value: '0.00',
    },
    phoneCode: '502',
  },
  {
    id: 'GU',
    name: 'Guam',
    type: 'CP',
    timezone: 'Pacific/Guam',
    timezones: ['Pacific/Guam'],
    languages: ['ch', 'en'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'GW',
    name: 'Guinea-Bissau',
    type: 'C',
    timezone: 'Africa/Bissau',
    timezones: ['Africa/Bissau'],
    languages: ['pt'],
    currency: {
      code: 'GWP',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '245',
  },
  {
    id: 'GY',
    name: 'Guyana',
    type: 'C',
    timezone: 'America/Guyana',
    timezones: ['America/Guyana'],
    languages: ['en'],
    currency: {
      code: 'GYD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '592',
  },
  {
    id: 'HK',
    name: 'Hong Kong SAR China',
    type: 'C',
    timezone: 'Asia/Hong_Kong',
    timezones: ['Asia/Hong_Kong'],
    languages: ['en', 'zh'],
    currency: {
      code: 'HKD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '852',
  },
  {
    id: 'HM',
    name: 'Heard Island and McDonald Islands',
    type: '',
    timezone: null,
    timezones: [],
    languages: ['und'],
    currency: {
      code: 'AUD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'HN',
    name: 'Honduras',
    type: 'C',
    timezone: 'America/Tegucigalpa',
    timezones: ['America/Tegucigalpa'],
    languages: ['en', 'es'],
    currency: {
      code: 'HNL',
      symbol: 'HNL',
      value: '0.00',
    },
    phoneCode: '504',
  },
  {
    id: 'HT',
    name: 'Haiti',
    type: 'C',
    timezone: 'America/Port-au-Prince',
    timezones: ['America/Port-au-Prince'],
    languages: ['fr', 'ht'],
    currency: {
      code: 'HTG',
      symbol: 'HTG',
      value: '0.00',
    },
    phoneCode: '509',
  },
  {
    id: 'HU',
    name: 'Hungary',
    type: 'CP',
    timezone: 'Europe/Budapest',
    timezones: ['Europe/Budapest'],
    languages: ['hu'],
    currency: {
      code: 'HUF',
      symbol: 'Ft',
      value: '0.00',
    },
    phoneCode: '36',
  },
  {
    id: 'ID',
    name: 'Indonesia',
    type: 'CP',
    timezone: 'Asia/Jakarta',
    timezones: [
      'Asia/Jakarta',
      'Asia/Jayapura',
      'Asia/Makassar',
      'Asia/Pontianak',
    ],
    languages: [
      'ace',
      'ban',
      'bug',
      'id',
      'jv',
      'mad',
      'mak',
      'min',
      'sas',
      'su',
    ],
    currency: {
      code: 'IDR',
      symbol: 'Rp',
      value: '0.00',
    },
    phoneCode: '62',
  },
  {
    id: 'IE',
    name: 'Ireland',
    type: 'S',
    timezone: 'Europe/Dublin',
    timezones: ['Europe/Dublin'],
    languages: ['en', 'ga'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '353',
  },
  {
    id: 'IL',
    name: 'Israel',
    type: 'CP',
    timezone: 'Asia/Jerusalem',
    timezones: ['Asia/Jerusalem'],
    languages: ['ar', 'he'],
    currency: {
      code: 'ILS',
      symbol: '₪',
      value: '0.00',
    },
    phoneCode: '972',
  },
  {
    id: 'IM',
    name: 'Isle of Man',
    type: '',
    timezone: 'Europe/Isle_of_Man',
    timezones: ['Europe/Isle_of_Man'],
    languages: ['en'],
    currency: {
      code: 'GBP',
      symbol: '£',
      value: '0.00',
    },
    phoneCode: '44',
  },
  {
    id: 'IN',
    name: 'India',
    type: 'CP',
    timezone: 'Asia/Calcutta',
    timezones: ['Asia/Calcutta'],
    languages: [
      'as',
      'awa',
      'bho',
      'bn',
      'doi',
      'gon',
      'gu',
      'hi',
      'kha',
      'kn',
      'kok',
      'kru',
      'ks',
      'mag',
      'mai',
      'ml',
      'mni',
      'mr',
      'mwr',
      'or',
      'pa',
      'sa',
      'sat',
      'sd',
      'ta',
      'te',
      'ur',
    ],
    currency: {
      code: 'INR',
      symbol: 'Rs',
      value: '0.00',
    },
    phoneCode: '91',
  },
  {
    id: 'IQ',
    name: 'Iraq',
    type: 'C',
    timezone: 'Asia/Baghdad',
    timezones: ['Asia/Baghdad'],
    languages: ['ar', 'ku'],
    currency: {
      code: 'IQD',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '964',
  },
  {
    id: 'IR',
    name: 'Iran',
    type: 'C',
    timezone: 'Asia/Tehran',
    timezones: ['Asia/Tehran'],
    languages: ['bal', 'fa', 'ku'],
    currency: {
      code: 'IRR',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '98',
  },
  {
    id: 'IS',
    name: 'Iceland',
    type: 'CP',
    timezone: 'Atlantic/Reykjavik',
    timezones: ['Atlantic/Reykjavik'],
    languages: ['is'],
    currency: {
      code: 'ISK',
      symbol: 'Ikr',
      value: '0.00',
    },
    phoneCode: '354',
  },
  {
    id: 'IT',
    name: 'Italy',
    type: 'CP',
    timezone: 'Europe/Rome',
    timezones: ['Europe/Rome'],
    languages: ['it', 'nap', 'scn'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '39',
  },
  {
    id: 'JE',
    name: 'Jersey',
    type: 'CP',
    timezone: 'Europe/Jersey',
    timezones: ['Europe/Jersey'],
    languages: ['en'],
    currency: {
      code: 'GBP',
      symbol: '£',
      value: '0.00',
    },
    phoneCode: '44',
  },
  {
    id: 'JM',
    name: 'Jamaica',
    type: 'C',
    timezone: 'America/Jamaica',
    timezones: ['America/Jamaica'],
    languages: ['en'],
    currency: {
      code: 'JMD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'JO',
    name: 'Jordan',
    type: 'CP',
    timezone: 'Asia/Amman',
    timezones: ['Asia/Amman'],
    languages: ['ar'],
    currency: {
      code: 'JOD',
      symbol: 'JD',
      value: '0.00',
    },
    phoneCode: '962',
  },
  {
    id: 'JP',
    name: 'Japan',
    type: 'CP',
    timezone: 'Asia/Tokyo',
    timezones: ['Asia/Tokyo'],
    languages: ['ja'],
    currency: {
      code: 'JPY',
      symbol: '¥',
      value: '0.00',
    },
    phoneCode: '81',
  },
  {
    id: 'JT',
    name: 'Johnston Island',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'KE',
    name: 'Kenya',
    type: 'C',
    timezone: 'Africa/Nairobi',
    timezones: ['Africa/Nairobi'],
    languages: ['en', 'kam', 'ki', 'luo', 'sw'],
    currency: {
      code: 'KES',
      symbol: 'Ksh',
      value: '0.00',
    },
    phoneCode: '254',
  },
  {
    id: 'KG',
    name: 'Kyrgyzstan',
    type: 'CP',
    timezone: 'Asia/Bishkek',
    timezones: ['Asia/Bishkek'],
    languages: ['ky', 'ru'],
    currency: {
      code: 'KGS',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '996',
  },
  {
    id: 'KI',
    name: 'Kiribati',
    type: 'C',
    timezone: 'Pacific/Enderbury',
    timezones: ['Pacific/Enderbury', 'Pacific/Kiritimati', 'Pacific/Tarawa'],
    languages: ['en', 'gil'],
    currency: {
      code: 'AUD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '686',
  },
  {
    id: 'KW',
    name: 'Kuwait',
    type: 'C',
    timezone: 'Asia/Kuwait',
    timezones: ['Asia/Kuwait'],
    languages: ['ar'],
    currency: {
      code: 'KWD',
      symbol: 'KD',
      value: '0.00',
    },
    phoneCode: '965',
  },
  {
    id: 'KZ',
    name: 'Kazakhstan',
    type: 'CP',
    timezone: 'Asia/Almaty',
    timezones: [
      'Asia/Almaty',
      'Asia/Aqtau',
      'Asia/Aqtobe',
      'Asia/Oral',
      'Asia/Qyzylorda',
    ],
    languages: ['kk', 'ru'],
    currency: {
      code: 'KZT',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '7',
  },
  {
    id: 'LA',
    name: 'Laos',
    type: 'C',
    timezone: 'Asia/Vientiane',
    timezones: ['Asia/Vientiane'],
    languages: ['lo'],
    currency: {
      code: 'LAK',
      symbol: '₭',
      value: '0.00',
    },
    phoneCode: '856',
  },
  {
    id: 'LB',
    name: 'Lebanon',
    type: 'C',
    timezone: 'Asia/Beirut',
    timezones: ['Asia/Beirut'],
    languages: ['ar'],
    currency: {
      code: 'LBP',
      symbol: 'LB£',
      value: '0.00',
    },
    phoneCode: '961',
  },
  {
    id: 'LI',
    name: 'Liechtenstein',
    type: 'CP',
    timezone: 'Europe/Vaduz',
    timezones: ['Europe/Vaduz'],
    languages: ['de', 'gsw'],
    currency: {
      code: 'CHF',
      symbol: 'Fr.',
      value: '0.00',
    },
    phoneCode: '423',
  },
  {
    id: 'LR',
    name: 'Liberia',
    type: 'C',
    timezone: 'Africa/Monrovia',
    timezones: ['Africa/Monrovia'],
    languages: ['en'],
    currency: {
      code: 'LRD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '231',
  },
  {
    id: 'LS',
    name: 'Lesotho',
    type: 'C',
    timezone: 'Africa/Maseru',
    timezones: ['Africa/Maseru'],
    languages: ['en', 'st'],
    currency: {
      code: 'ZAR',
      symbol: 'R',
      value: '0.00',
    },
    phoneCode: '266',
  },
  {
    id: 'LT',
    name: 'Lithuania',
    type: 'CP',
    timezone: 'Europe/Vilnius',
    timezones: ['Europe/Vilnius'],
    languages: ['lt'],
    currency: {
      code: 'LTL',
      symbol: 'Lt',
      value: '0.00',
    },
    phoneCode: '370',
  },
  {
    id: 'LU',
    name: 'Luxembourg',
    type: 'CP',
    timezone: 'Europe/Luxembourg',
    timezones: ['Europe/Luxembourg'],
    languages: ['de', 'fr', 'lb'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '352',
  },
  {
    id: 'LV',
    name: 'Latvia',
    type: 'CP',
    timezone: 'Europe/Riga',
    timezones: ['Europe/Riga'],
    languages: ['lv'],
    currency: {
      code: 'LVL',
      symbol: 'Ls',
      value: '0.00',
    },
    phoneCode: '371',
  },
  {
    id: 'LY',
    name: 'Libya',
    type: 'C',
    timezone: 'Africa/Tripoli',
    timezones: ['Africa/Tripoli'],
    languages: ['ar'],
    currency: {
      code: 'LYD',
      symbol: 'LD',
      value: '0.00',
    },
    phoneCode: '218',
  },
  {
    id: 'FM',
    name: 'Micronesia',
    type: 'CP',
    timezone: 'Pacific/Kosrae',
    timezones: ['Pacific/Kosrae', 'Pacific/Ponape', 'Pacific/Truk'],
    languages: ['chk', 'en', 'kos', 'pon', 'yap'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '691',
  },
  {
    id: 'FX',
    name: 'Metropolitan France',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'MA',
    name: 'Morocco',
    type: 'CP',
    timezone: 'Africa/Casablanca',
    timezones: ['Africa/Casablanca'],
    languages: ['ar', 'fr'],
    currency: {
      code: 'MAD',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '212',
  },
  {
    id: 'MC',
    name: 'Monaco',
    type: 'CP',
    timezone: 'Europe/Monaco',
    timezones: ['Europe/Monaco'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '377',
  },
  {
    id: 'MD',
    name: 'Moldova',
    type: 'CP',
    timezone: 'Europe/Chisinau',
    timezones: ['Europe/Chisinau'],
    languages: ['ro'],
    currency: {
      code: 'MDL',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '373',
  },
  {
    id: 'ME',
    name: 'Montenegro',
    type: 'CP',
    timezone: 'Europe/Podgorica',
    timezones: ['Europe/Podgorica'],
    languages: ['sr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '382',
  },
  {
    id: 'MG',
    name: 'Madagascar',
    type: 'CP',
    timezone: 'Indian/Antananarivo',
    timezones: ['Indian/Antananarivo'],
    languages: ['en', 'fr', 'mg'],
    currency: {
      code: 'MGA',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '261',
  },
  {
    id: 'MH',
    name: 'Marshall Islands',
    type: 'CP',
    timezone: 'Pacific/Kwajalein',
    timezones: ['Pacific/Kwajalein', 'Pacific/Majuro'],
    languages: ['en', 'mh'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '692',
  },
  {
    id: 'MI',
    name: 'Midway Islands',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'MK',
    name: 'Macedonia',
    type: 'CP',
    timezone: 'Europe/Skopje',
    timezones: ['Europe/Skopje'],
    languages: ['mk', 'sq'],
    currency: {
      code: 'MKD',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '389',
  },
  {
    id: 'ML',
    name: 'Mali',
    type: 'C',
    timezone: 'Africa/Bamako',
    timezones: ['Africa/Bamako'],
    languages: ['bm', 'fr'],
    currency: {
      code: 'XOF',
      symbol: 'CFA',
      value: '0.00',
    },
    phoneCode: '223',
  },
  {
    id: 'MM',
    name: 'Myanmar [Burma]',
    type: 'C',
    timezone: 'Asia/Rangoon',
    timezones: ['Asia/Rangoon'],
    languages: ['my', 'shn'],
    currency: {
      code: 'MMK',
      symbol: 'MMK',
      value: '0.00',
    },
    phoneCode: '95',
  },
  {
    id: 'MN',
    name: 'Mongolia',
    type: 'CP',
    timezone: 'Asia/Choibalsan',
    timezones: ['Asia/Choibalsan', 'Asia/Hovd', 'Asia/Ulaanbaatar'],
    languages: ['mn'],
    currency: {
      code: 'MNT',
      symbol: '₮',
      value: '0.00',
    },
    phoneCode: '976',
  },
  {
    id: 'MO',
    name: 'Macau SAR China',
    type: 'C',
    timezone: 'Asia/Macau',
    timezones: ['Asia/Macau'],
    languages: ['zh'],
    currency: {
      code: 'MOP',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '853',
  },
  {
    id: 'MQ',
    name: 'Martinique',
    type: 'CP',
    timezone: 'America/Martinique',
    timezones: ['America/Martinique'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '596',
  },
  {
    id: 'MR',
    name: 'Mauritania',
    type: 'C',
    timezone: 'Africa/Nouakchott',
    timezones: ['Africa/Nouakchott'],
    languages: ['ar'],
    currency: {
      code: 'MRO',
      symbol: 'UM',
      value: '0.00',
    },
    phoneCode: '222',
  },
  {
    id: 'MS',
    name: 'Montserrat',
    type: 'C',
    timezone: 'America/Montserrat',
    timezones: ['America/Montserrat'],
    languages: ['en'],
    currency: {
      code: 'XCD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'MT',
    name: 'Malta',
    type: 'C',
    timezone: 'Europe/Malta',
    timezones: ['Europe/Malta'],
    languages: ['en', 'mt'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '356',
  },
  {
    id: 'MU',
    name: 'Mauritius',
    type: 'C',
    timezone: 'Indian/Mauritius',
    timezones: ['Indian/Mauritius'],
    languages: ['bho', 'en', 'fr', 'mfe'],
    currency: {
      code: 'MUR',
      symbol: 'MURs',
      value: '0.00',
    },
    phoneCode: '230',
  },
  {
    id: 'MV',
    name: 'Maldives',
    type: 'CP',
    timezone: 'Indian/Maldives',
    timezones: ['Indian/Maldives'],
    languages: ['dv'],
    currency: {
      code: 'MVR',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '960',
  },
  {
    id: 'MW',
    name: 'Malawi',
    type: 'C',
    timezone: 'Africa/Blantyre',
    timezones: ['Africa/Blantyre'],
    languages: ['en', 'ny', 'tum'],
    currency: {
      code: 'MWK',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '265',
  },
  {
    id: 'MX',
    name: 'Mexico',
    type: 'CP',
    timezone: 'America/Cancun',
    timezones: [
      'America/Cancun',
      'America/Chihuahua',
      'America/Hermosillo',
      'America/Mazatlan',
      'America/Merida',
      'America/Mexico_City',
      'America/Monterrey',
      'America/Tijuana',
    ],
    languages: ['es'],
    currency: {
      code: 'MXN',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '52',
  },
  {
    id: 'MY',
    name: 'Malaysia',
    type: 'CP',
    timezone: 'Asia/Kuala_Lumpur',
    timezones: ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
    languages: ['ms'],
    currency: {
      code: 'MYR',
      symbol: 'RM',
      value: '0.00',
    },
    phoneCode: '60',
  },
  {
    id: 'MZ',
    name: 'Mozambique',
    type: 'C',
    timezone: 'Africa/Maputo',
    timezones: ['Africa/Maputo'],
    languages: ['pt'],
    currency: {
      code: 'MZN',
      symbol: 'MTn',
      value: '0.00',
    },
    phoneCode: '258',
  },
  {
    id: 'YT',
    name: 'Mayotte',
    type: 'CP',
    timezone: 'Indian/Mayotte',
    timezones: ['Indian/Mayotte'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '262',
  },
  {
    id: 'AN',
    name: 'Netherlands Antilles',
    type: 'C',
    timezone: 'America/Curacao',
    timezones: ['America/Curacao'],
    languages: ['nl', 'pap'],
    currency: {
      code: 'ANG',
      symbol: 'NAf.',
      value: '0.00',
    },
    phoneCode: '599',
  },
  {
    id: 'KP',
    name: 'North Korea',
    type: 'C',
    timezone: 'Asia/Pyongyang',
    timezones: ['Asia/Pyongyang'],
    languages: ['ko'],
    currency: {
      code: 'KPW',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '850',
  },
  {
    id: 'MP',
    name: 'Northern Mariana Islands',
    type: 'CP',
    timezone: 'Pacific/Saipan',
    timezones: ['Pacific/Saipan'],
    languages: ['en'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'NA',
    name: 'Namibia',
    type: 'C',
    timezone: 'Africa/Windhoek',
    timezones: ['Africa/Windhoek'],
    languages: ['en', 'kj', 'ng'],
    currency: {
      code: 'NAD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '264',
  },
  {
    id: 'NC',
    name: 'New Caledonia',
    type: 'CP',
    timezone: 'Pacific/Noumea',
    timezones: ['Pacific/Noumea'],
    languages: ['fr'],
    currency: {
      code: 'XPF',
      symbol: 'CFPF',
      value: '0.00',
    },
    phoneCode: '687',
  },
  {
    id: 'NE',
    name: 'Niger',
    type: 'C',
    timezone: 'Africa/Niamey',
    timezones: ['Africa/Niamey'],
    languages: ['fr'],
    currency: {
      code: 'XOF',
      symbol: 'CFA',
      value: '0.00',
    },
    phoneCode: '227',
  },
  {
    id: 'NF',
    name: 'Norfolk Island',
    type: '',
    timezone: 'Pacific/Norfolk',
    timezones: ['Pacific/Norfolk'],
    languages: ['en'],
    currency: {
      code: 'AUD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '672',
  },
  {
    id: 'NG',
    name: 'Nigeria',
    type: 'C',
    timezone: 'Africa/Lagos',
    timezones: ['Africa/Lagos'],
    languages: ['bin', 'efi', 'en', 'ha', 'ig', 'tiv', 'yo'],
    currency: {
      code: 'NGN',
      symbol: '₦',
      value: '0.00',
    },
    phoneCode: '234',
  },
  {
    id: 'NI',
    name: 'Nicaragua',
    type: 'C',
    timezone: 'America/Managua',
    timezones: ['America/Managua'],
    languages: ['es'],
    currency: {
      code: 'NIO',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '505',
  },
  {
    id: 'NL',
    name: 'Netherlands',
    type: 'CP',
    timezone: 'Europe/Amsterdam',
    timezones: ['Europe/Amsterdam'],
    languages: ['fy', 'nl'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '31',
  },
  {
    id: 'NO',
    name: 'Norway',
    type: 'CP',
    timezone: 'Europe/Oslo',
    timezones: ['Europe/Oslo'],
    languages: ['nb', 'nn', 'se'],
    currency: {
      code: 'NOK',
      symbol: 'Nkr',
      value: '0.00',
    },
    phoneCode: '47',
  },
  {
    id: 'NP',
    name: 'Nepal',
    type: 'C',
    timezone: 'Asia/Katmandu',
    timezones: ['Asia/Katmandu'],
    languages: ['bho', 'mai', 'ne'],
    currency: {
      code: 'NPR',
      symbol: 'NPRs',
      value: '0.00',
    },
    phoneCode: '977',
  },
  {
    id: 'NR',
    name: 'Nauru',
    type: 'C',
    timezone: 'Pacific/Nauru',
    timezones: ['Pacific/Nauru'],
    languages: ['en', 'na'],
    currency: {
      code: 'AUD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '674',
  },
  {
    id: 'NT',
    name: 'Neutral Zone',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'NU',
    name: 'Niue',
    type: 'C',
    timezone: 'Pacific/Niue',
    timezones: ['Pacific/Niue'],
    languages: ['en', 'niu'],
    currency: {
      code: 'NZD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '683',
  },
  {
    id: 'NZ',
    name: 'New Zealand',
    type: 'CP',
    timezone: 'Pacific/Auckland',
    timezones: ['Pacific/Auckland', 'Pacific/Chatham'],
    languages: ['en', 'mi'],
    currency: {
      code: 'NZD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '64',
  },
  {
    id: 'VD',
    name: 'North Vietnam',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'OM',
    name: 'Oman',
    type: 'C',
    timezone: 'Asia/Muscat',
    timezones: ['Asia/Muscat'],
    languages: ['ar'],
    currency: {
      code: 'OMR',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '968',
  },
  {
    id: 'PA',
    name: 'Panama',
    type: 'C',
    timezone: 'America/Panama',
    timezones: ['America/Panama'],
    languages: ['es'],
    currency: {
      code: 'PAB',
      symbol: 'B/.',
      value: '0.00',
    },
    phoneCode: '507',
  },
  {
    id: 'PC',
    name: 'Pacific Islands Trust Territory',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'PE',
    name: 'Peru',
    type: 'C',
    timezone: 'America/Lima',
    timezones: ['America/Lima'],
    languages: ['es', 'qu'],
    currency: {
      code: 'PEN',
      symbol: 'S/.',
      value: '0.00',
    },
    phoneCode: '51',
  },
  {
    id: 'PG',
    name: 'Papua New Guinea',
    type: 'CP',
    timezone: 'Pacific/Port_Moresby',
    timezones: ['Pacific/Port_Moresby'],
    languages: ['en', 'ho', 'tpi'],
    currency: {
      code: 'PGK',
      symbol: 'PGK',
      value: '0.00',
    },
    phoneCode: '675',
  },
  {
    id: 'PH',
    name: 'Philippines',
    type: 'CP',
    timezone: 'Asia/Manila',
    timezones: ['Asia/Manila'],
    languages: [
      'ceb',
      'en',
      'es',
      'fil',
      'hil',
      'ilo',
      'pag',
      'pam',
      'tl',
      'war',
    ],
    currency: {
      code: 'PHP',
      symbol: '₱',
      value: '0.00',
    },
    phoneCode: '63',
  },
  {
    id: 'PK',
    name: 'Pakistan',
    type: 'P',
    timezone: 'Asia/Karachi',
    timezones: ['Asia/Karachi'],
    languages: ['bal', 'en', 'lah', 'ur'],
    currency: {
      code: 'PKR',
      symbol: 'PKRs',
      value: '0.00',
    },
    phoneCode: '92',
  },
  {
    id: 'PL',
    name: 'Poland',
    type: 'CP',
    timezone: 'Europe/Warsaw',
    timezones: ['Europe/Warsaw'],
    languages: ['pl'],
    currency: {
      code: 'PLN',
      symbol: 'zł',
      value: '0.00',
    },
    phoneCode: '48',
  },
  {
    id: 'PN',
    name: 'Pitcairn Islands',
    type: '',
    timezone: 'Pacific/Pitcairn',
    timezones: ['Pacific/Pitcairn'],
    languages: ['en'],
    currency: {
      code: 'NZD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'PR',
    name: 'Puerto Rico',
    type: 'CP',
    timezone: 'America/Puerto_Rico',
    timezones: ['America/Puerto_Rico'],
    languages: ['en', 'es'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'PS',
    name: 'Palestinian Territories',
    type: '',
    timezone: 'Asia/Gaza',
    timezones: ['Asia/Gaza'],
    languages: ['ar'],
    currency: {
      code: 'JOD',
      symbol: 'JD',
      value: '0.00',
    },
    phoneCode: '972',
  },
  {
    id: 'PT',
    name: 'Portugal',
    type: 'CP',
    timezone: 'Atlantic/Azores',
    timezones: ['Atlantic/Azores', 'Atlantic/Madeira', 'Europe/Lisbon'],
    languages: ['pt'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '351',
  },
  {
    id: 'PW',
    name: 'Palau',
    type: 'CP',
    timezone: 'Pacific/Palau',
    timezones: ['Pacific/Palau'],
    languages: ['pau'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '680',
  },
  {
    id: 'PY',
    name: 'Paraguay',
    type: 'C',
    timezone: 'America/Asuncion',
    timezones: ['America/Asuncion'],
    languages: ['es', 'gn'],
    currency: {
      code: 'PYG',
      symbol: '₲',
      value: '0.00',
    },
    phoneCode: '595',
  },
  {
    id: 'PZ',
    name: 'Panama Canal Zone',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'YD',
    name: "People's Democratic Republic of Yemen",
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: 'YDD',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'QA',
    name: 'Qatar',
    type: 'C',
    timezone: 'Asia/Qatar',
    timezones: ['Asia/Qatar'],
    languages: ['ar'],
    currency: {
      code: 'QAR',
      symbol: 'QR',
      value: '0.00',
    },
    phoneCode: '974',
  },
  {
    id: 'RE',
    name: 'Réunion',
    type: 'CP',
    timezone: 'Indian/Reunion',
    timezones: ['Indian/Reunion'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '262',
  },
  {
    id: 'RO',
    name: 'Romania',
    type: 'CP',
    timezone: 'Europe/Bucharest',
    timezones: ['Europe/Bucharest'],
    languages: ['ro'],
    currency: {
      code: 'RON',
      symbol: 'RON',
      value: '0.00',
    },
    phoneCode: '40',
  },
  {
    id: 'RU',
    name: 'Russia',
    type: 'CP',
    timezone: 'Asia/Anadyr',
    timezones: [
      'Asia/Anadyr',
      'Asia/Irkutsk',
      'Asia/Kamchatka',
      'Asia/Krasnoyarsk',
      'Asia/Magadan',
      'Asia/Novosibirsk',
      'Asia/Omsk',
      'Asia/Sakhalin',
      'Asia/Vladivostok',
      'Asia/Yakutsk',
      'Asia/Yekaterinburg',
      'Europe/Kaliningrad',
      'Europe/Moscow',
      'Europe/Samara',
      'Europe/Volgograd',
    ],
    languages: [
      'ady',
      'av',
      'ba',
      'ce',
      'cv',
      'inh',
      'kbd',
      'krc',
      'kum',
      'lez',
      'mdf',
      'myv',
      'ru',
      'sah',
      'tt',
      'tyv',
      'udm',
    ],
    currency: {
      code: 'RUB',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '7',
  },
  {
    id: 'RW',
    name: 'Rwanda',
    type: 'C',
    timezone: 'Africa/Kigali',
    timezones: ['Africa/Kigali'],
    languages: ['en', 'fr', 'rw'],
    currency: {
      code: 'RWF',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '250',
  },
  {
    id: 'BL',
    name: 'Saint Barthélemy',
    type: '',
    timezone: 'America/St_Barthelemy',
    timezones: ['America/St_Barthelemy'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '590',
  },
  {
    id: 'CH',
    name: 'Switzerland',
    type: 'CP',
    timezone: 'Europe/Zurich',
    timezones: ['Europe/Zurich'],
    languages: ['de', 'fr', 'gsw', 'it', 'rm'],
    currency: {
      code: 'CHF',
      symbol: 'Fr.',
      value: '0.00',
    },
    phoneCode: '41',
  },
  {
    id: 'CS',
    name: 'Serbia and Montenegro',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: 'CSD',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'ES',
    name: 'Spain',
    type: 'CP',
    timezone: 'Africa/Ceuta',
    timezones: ['Africa/Ceuta', 'Atlantic/Canary', 'Europe/Madrid'],
    languages: ['ast', 'es', 'eu', 'gl'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '34',
  },
  {
    id: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    type: '',
    timezone: 'Atlantic/South_Georgia',
    timezones: ['Atlantic/South_Georgia'],
    languages: ['und'],
    currency: {
      code: 'GBP',
      symbol: '£',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'KN',
    name: 'Saint Kitts and Nevis',
    type: 'C',
    timezone: 'America/St_Kitts',
    timezones: ['America/St_Kitts'],
    languages: ['en'],
    currency: {
      code: 'XCD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'KR',
    name: 'South Korea',
    type: 'CP',
    timezone: 'Asia/Seoul',
    timezones: ['Asia/Seoul'],
    languages: ['ko'],
    currency: {
      code: 'KRW',
      symbol: '₩',
      value: '0.00',
    },
    phoneCode: '82',
  },
  {
    id: 'LC',
    name: 'Saint Lucia',
    type: 'C',
    timezone: 'America/St_Lucia',
    timezones: ['America/St_Lucia'],
    languages: ['en'],
    currency: {
      code: 'XCD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'LK',
    name: 'Sri Lanka',
    type: 'CP',
    timezone: 'Asia/Colombo',
    timezones: ['Asia/Colombo'],
    languages: ['si', 'ta'],
    currency: {
      code: 'LKR',
      symbol: 'SLRs',
      value: '0.00',
    },
    phoneCode: '94',
  },
  {
    id: 'MF',
    name: 'Saint Martin',
    type: '',
    timezone: 'America/Marigot',
    timezones: ['America/Marigot'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'PM',
    name: 'Saint Pierre and Miquelon',
    type: '',
    timezone: 'America/Miquelon',
    timezones: ['America/Miquelon'],
    languages: ['fr'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '508',
  },
  {
    id: 'RS',
    name: 'Serbia',
    type: 'CP',
    timezone: 'Europe/Belgrade',
    timezones: ['Europe/Belgrade'],
    languages: ['sr'],
    currency: {
      code: 'RSD',
      symbol: 'din.',
      value: '0.00',
    },
    phoneCode: '381',
  },
  {
    id: 'SA',
    name: 'Saudi Arabia',
    type: 'CP',
    timezone: 'Asia/Riyadh',
    timezones: ['Asia/Riyadh'],
    languages: ['ar'],
    currency: {
      code: 'SAR',
      symbol: 'SR',
      value: '0.00',
    },
    phoneCode: '966',
  },
  {
    id: 'SB',
    name: 'Solomon Islands',
    type: 'C',
    timezone: 'Pacific/Guadalcanal',
    timezones: ['Pacific/Guadalcanal'],
    languages: ['en'],
    currency: {
      code: 'SBD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '677',
  },
  {
    id: 'SC',
    name: 'Seychelles',
    type: 'C',
    timezone: 'Indian/Mahe',
    timezones: ['Indian/Mahe'],
    languages: ['en', 'fr'],
    currency: {
      code: 'SCR',
      symbol: 'SRe',
      value: '0.00',
    },
    phoneCode: '248',
  },
  {
    id: 'SD',
    name: 'Sudan',
    type: 'C',
    timezone: 'Africa/Khartoum',
    timezones: ['Africa/Khartoum'],
    languages: ['ar'],
    currency: {
      code: 'SDG',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '249',
  },
  {
    id: 'SE',
    name: 'Sweden',
    type: 'CP',
    timezone: 'Europe/Stockholm',
    timezones: ['Europe/Stockholm'],
    languages: ['sv'],
    currency: {
      code: 'SEK',
      symbol: 'Skr',
      value: '0.00',
    },
    phoneCode: '46',
  },
  {
    id: 'SG',
    name: 'Singapore',
    type: 'CP',
    timezone: 'Asia/Singapore',
    timezones: ['Asia/Singapore'],
    languages: ['en', 'ms', 'ta', 'zh'],
    currency: {
      code: 'SGD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '65',
  },
  {
    id: 'SH',
    name: 'Saint Helena',
    type: 'S',
    timezone: 'Atlantic/St_Helena',
    timezones: ['Atlantic/St_Helena'],
    languages: ['en'],
    currency: {
      code: 'SHP',
      symbol: 'SH£',
      value: '0.00',
    },
    phoneCode: '290',
  },
  {
    id: 'SI',
    name: 'Slovenia',
    type: 'CP',
    timezone: 'Europe/Ljubljana',
    timezones: ['Europe/Ljubljana'],
    languages: ['sl'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '386',
  },
  {
    id: 'SJ',
    name: 'Svalbard and Jan Mayen',
    type: '',
    timezone: 'Arctic/Longyearbyen',
    timezones: ['Arctic/Longyearbyen'],
    languages: ['nb'],
    currency: {
      code: 'NOK',
      symbol: 'Nkr',
      value: '0.00',
    },
    phoneCode: '47',
  },
  {
    id: 'SK',
    name: 'Slovakia',
    type: 'CP',
    timezone: 'Europe/Bratislava',
    timezones: ['Europe/Bratislava'],
    languages: ['sk'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '421',
  },
  {
    id: 'SL',
    name: 'Sierra Leone',
    type: 'C',
    timezone: 'Africa/Freetown',
    timezones: ['Africa/Freetown'],
    languages: ['en', 'men', 'tem'],
    currency: {
      code: 'SLL',
      symbol: 'Le',
      value: '0.00',
    },
    phoneCode: '232',
  },
  {
    id: 'SM',
    name: 'San Marino',
    type: 'CP',
    timezone: 'Europe/San_Marino',
    timezones: ['Europe/San_Marino'],
    languages: ['it'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '378',
  },
  {
    id: 'SN',
    name: 'Senegal',
    type: 'C',
    timezone: 'Africa/Dakar',
    timezones: ['Africa/Dakar'],
    languages: ['fr', 'srr', 'wo'],
    currency: {
      code: 'XOF',
      symbol: 'CFA',
      value: '0.00',
    },
    phoneCode: '221',
  },
  {
    id: 'SO',
    name: 'Somalia',
    type: 'C',
    timezone: 'Africa/Mogadishu',
    timezones: ['Africa/Mogadishu'],
    languages: ['so'],
    currency: {
      code: 'SOS',
      symbol: 'Ssh',
      value: '0.00',
    },
    phoneCode: '252',
  },
  {
    id: 'SR',
    name: 'Suriname',
    type: 'C',
    timezone: 'America/Paramaribo',
    timezones: ['America/Paramaribo'],
    languages: ['nl', 'srn'],
    currency: {
      code: 'SRD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '597',
  },
  {
    id: 'ST',
    name: 'São Tomé and Príncipe',
    type: 'C',
    timezone: 'Africa/Sao_Tome',
    timezones: ['Africa/Sao_Tome'],
    languages: ['pt'],
    currency: {
      code: 'STD',
      symbol: 'Db',
      value: '0.00',
    },
    phoneCode: '239',
  },
  {
    id: 'SY',
    name: 'Syria',
    type: 'C',
    timezone: 'Asia/Damascus',
    timezones: ['Asia/Damascus'],
    languages: ['ar', 'fr', 'ku'],
    currency: {
      code: 'SYP',
      symbol: 'SY£',
      value: '0.00',
    },
    phoneCode: '963',
  },
  {
    id: 'SZ',
    name: 'Swaziland',
    type: 'CP',
    timezone: 'Africa/Mbabane',
    timezones: ['Africa/Mbabane'],
    languages: ['en', 'ss'],
    currency: {
      code: 'SZL',
      symbol: 'SZL',
      value: '0.00',
    },
    phoneCode: '268',
  },
  {
    id: 'VC',
    name: 'Saint Vincent and the Grenadines',
    type: 'C',
    timezone: 'America/St_Vincent',
    timezones: ['America/St_Vincent'],
    languages: ['en'],
    currency: {
      code: 'XCD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'WS',
    name: 'Samoa',
    type: 'C',
    timezone: 'Pacific/Apia',
    timezones: ['Pacific/Apia'],
    languages: ['en', 'sm'],
    currency: {
      code: 'WST',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '685',
  },
  {
    id: 'ZA',
    name: 'South Africa',
    type: 'CP',
    timezone: 'Africa/Johannesburg',
    timezones: ['Africa/Johannesburg'],
    languages: ['af', 'en', 'nso', 'ss', 'st', 'tn', 'ts', 've', 'xh', 'zu'],
    currency: {
      code: 'ZAR',
      symbol: 'R',
      value: '0.00',
    },
    phoneCode: '27',
  },
  {
    id: 'TC',
    name: 'Turks and Caicos Islands',
    type: 'C',
    timezone: 'America/Grand_Turk',
    timezones: ['America/Grand_Turk'],
    languages: ['en'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'TG',
    name: 'Togo',
    type: 'C',
    timezone: 'Africa/Lome',
    timezones: ['Africa/Lome'],
    languages: ['ee', 'fr'],
    currency: {
      code: 'XOF',
      symbol: 'CFA',
      value: '0.00',
    },
    phoneCode: '228',
  },
  {
    id: 'TH',
    name: 'Thailand',
    type: 'CP',
    timezone: 'Asia/Bangkok',
    timezones: ['Asia/Bangkok'],
    languages: ['th'],
    currency: {
      code: 'THB',
      symbol: '฿',
      value: '0.00',
    },
    phoneCode: '66',
  },
  {
    id: 'TJ',
    name: 'Tajikistan',
    type: 'CP',
    timezone: 'Asia/Dushanbe',
    timezones: ['Asia/Dushanbe'],
    languages: ['tg'],
    currency: {
      code: 'TJS',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '992',
  },
  {
    id: 'TK',
    name: 'Tokelau',
    type: '',
    timezone: 'Pacific/Fakaofo',
    timezones: ['Pacific/Fakaofo'],
    languages: ['en', 'tkl'],
    currency: {
      code: 'NZD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '690',
  },
  {
    id: 'TL',
    name: 'Timor-Leste',
    type: 'C',
    timezone: 'Asia/Dili',
    timezones: ['Asia/Dili'],
    languages: ['pt', 'tet'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '670',
  },
  {
    id: 'TM',
    name: 'Turkmenistan',
    type: '',
    timezone: 'Asia/Ashgabat',
    timezones: ['Asia/Ashgabat'],
    languages: ['tk'],
    currency: {
      code: 'TMT',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '993',
  },
  {
    id: 'TN',
    name: 'Tunisia',
    type: 'CP',
    timezone: 'Africa/Tunis',
    timezones: ['Africa/Tunis'],
    languages: ['ar', 'fr'],
    currency: {
      code: 'TND',
      symbol: 'DT',
      value: '0.00',
    },
    phoneCode: '216',
  },
  {
    id: 'TO',
    name: 'Tonga',
    type: 'C',
    timezone: 'Pacific/Tongatapu',
    timezones: ['Pacific/Tongatapu'],
    languages: ['en', 'to'],
    currency: {
      code: 'TOP',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '676',
  },
  {
    id: 'TR',
    name: 'Turkey',
    type: 'CP',
    timezone: 'Europe/Istanbul',
    timezones: ['Europe/Istanbul'],
    languages: ['ku', 'tr'],
    currency: {
      code: 'TRY',
      symbol: 'TL',
      value: '0.00',
    },
    phoneCode: '90',
  },
  {
    id: 'TT',
    name: 'Trinidad and Tobago',
    type: 'C',
    timezone: 'America/Port_of_Spain',
    timezones: ['America/Port_of_Spain'],
    languages: ['en'],
    currency: {
      code: 'TTD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'TV',
    name: 'Tuvalu',
    type: 'C',
    timezone: 'Pacific/Funafuti',
    timezones: ['Pacific/Funafuti'],
    languages: ['en', 'tvl'],
    currency: {
      code: 'AUD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '688',
  },
  {
    id: 'TW',
    name: 'Taiwan',
    type: 'CP',
    timezone: 'Asia/Taipei',
    timezones: ['Asia/Taipei'],
    languages: ['zh'],
    currency: {
      code: 'TWD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '886',
  },
  {
    id: 'TZ',
    name: 'Tanzania',
    type: 'C',
    timezone: 'Africa/Dar_es_Salaam',
    timezones: ['Africa/Dar_es_Salaam'],
    languages: ['en', 'nym', 'suk', 'sw'],
    currency: {
      code: 'TZS',
      symbol: 'TSh',
      value: '0.00',
    },
    phoneCode: '255',
  },
  {
    id: 'AE',
    name: 'United Arab Emirates',
    type: 'C',
    timezone: 'Asia/Dubai',
    timezones: ['Asia/Dubai'],
    languages: ['ar'],
    currency: {
      code: 'AED',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '971',
  },
  {
    id: 'GB',
    name: 'United Kingdom',
    type: 'CP',
    timezone: 'Europe/London',
    timezones: ['Europe/London'],
    languages: ['cy', 'en', 'gd', 'sco'],
    currency: {
      code: 'GBP',
      symbol: '£',
      value: '0.00',
    },
    phoneCode: '44',
  },
  {
    id: 'PU',
    name: 'U.S. Miscellaneous Pacific Islands',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'SU',
    name: 'Union of Soviet Socialist Republics',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: 'SUR',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'UA',
    name: 'Ukraine',
    type: 'CP',
    timezone: 'Europe/Kiev',
    timezones: [
      'Europe/Kiev',
      'Europe/Simferopol',
      'Europe/Uzhgorod',
      'Europe/Zaporozhye',
    ],
    languages: ['uk'],
    currency: {
      code: 'UAH',
      symbol: '₴',
      value: '0.00',
    },
    phoneCode: '380',
  },
  {
    id: 'UG',
    name: 'Uganda',
    type: 'C',
    timezone: 'Africa/Kampala',
    timezones: ['Africa/Kampala'],
    languages: ['en', 'lg', 'nyn', 'sw'],
    currency: {
      code: 'UGX',
      symbol: 'USh',
      value: '0.00',
    },
    phoneCode: '256',
  },
  {
    id: 'UM',
    name: 'U.S. Minor Outlying Islands',
    type: '',
    timezone: 'Pacific/Johnston',
    timezones: ['Pacific/Johnston', 'Pacific/Midway', 'Pacific/Wake'],
    languages: ['en'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'US',
    name: 'United States',
    type: 'CP',
    timezone: 'America/Adak',
    timezones: [
      'America/Adak',
      'America/Anchorage',
      'America/Boise',
      'America/Chicago',
      'America/Denver',
      'America/Detroit',
      'America/Indiana/Knox',
      'America/Indiana/Marengo',
      'America/Indiana/Petersburg',
      'America/Indiana/Tell_City',
      'America/Indiana/Vevay',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Indianapolis',
      'America/Juneau',
      'America/Kentucky/Monticello',
      'America/Los_Angeles',
      'America/Louisville',
      'America/Menominee',
      'America/New_York',
      'America/Nome',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/Phoenix',
      'America/Shiprock',
      'America/Yakutat',
      'Pacific/Honolulu',
    ],
    languages: ['en', 'haw', 'tl'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'UY',
    name: 'Uruguay',
    type: 'C',
    timezone: 'America/Montevideo',
    timezones: ['America/Montevideo'],
    languages: ['es'],
    currency: {
      code: 'UYU',
      symbol: '$U',
      value: '0.00',
    },
    phoneCode: '598',
  },
  {
    id: 'UZ',
    name: 'Uzbekistan',
    type: 'CP',
    timezone: 'Asia/Samarkand',
    timezones: ['Asia/Samarkand', 'Asia/Tashkent'],
    languages: ['uz'],
    currency: {
      code: 'UZS',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '998',
  },
  {
    id: 'VI',
    name: 'U.S. Virgin Islands',
    type: 'CP',
    timezone: 'America/St_Thomas',
    timezones: ['America/St_Thomas'],
    languages: ['en'],
    currency: {
      code: 'USD',
      symbol: '$',
      value: '0.00',
    },
    phoneCode: '1',
  },
  {
    id: 'ZZ',
    name: 'Unknown or Invalid Region',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: 'XAG',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'VA',
    name: 'Vatican City',
    type: '',
    timezone: 'Europe/Vatican',
    timezones: ['Europe/Vatican'],
    languages: ['la'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '39',
  },
  {
    id: 'VE',
    name: 'Venezuela',
    type: 'C',
    timezone: 'America/Caracas',
    timezones: ['America/Caracas'],
    languages: ['es'],
    currency: {
      code: 'VEF',
      symbol: 'Bs.F.',
      value: '0.00',
    },
    phoneCode: '58',
  },
  {
    id: 'VN',
    name: 'Vietnam',
    type: 'CP',
    timezone: 'Asia/Saigon',
    timezones: ['Asia/Saigon'],
    languages: ['vi'],
    currency: {
      code: 'VND',
      symbol: '₫',
      value: '0.00',
    },
    phoneCode: '84',
  },
  {
    id: 'VU',
    name: 'Vanuatu',
    type: 'C',
    timezone: 'Pacific/Efate',
    timezones: ['Pacific/Efate'],
    languages: ['bi', 'en', 'fr'],
    currency: {
      code: 'VUV',
      symbol: 'VT',
      value: '0.00',
    },
    phoneCode: '678',
  },
  {
    id: 'EH',
    name: 'Western Sahara',
    type: '',
    timezone: 'Africa/El_Aaiun',
    timezones: ['Africa/El_Aaiun'],
    languages: ['ar'],
    currency: {
      code: 'MAD',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'WF',
    name: 'Wallis and Futuna',
    type: '',
    timezone: 'Pacific/Wallis',
    timezones: ['Pacific/Wallis'],
    languages: ['fr'],
    currency: {
      code: 'XPF',
      symbol: 'CFPF',
      value: '0.00',
    },
    phoneCode: '681',
  },
  {
    id: 'WK',
    name: 'Wake Island',
    type: '',
    timezone: null,
    timezones: [],
    languages: [],
    currency: {
      code: '',
      symbol: '',
      value: '0.00',
    },
    phoneCode: null,
  },
  {
    id: 'YE',
    name: 'Yemen',
    type: 'C',
    timezone: 'Asia/Aden',
    timezones: ['Asia/Aden'],
    languages: ['ar'],
    currency: {
      code: 'YER',
      symbol: 'YR',
      value: '0.00',
    },
    phoneCode: '967',
  },
  {
    id: 'ZM',
    name: 'Zambia',
    type: 'C',
    timezone: 'Africa/Lusaka',
    timezones: ['Africa/Lusaka'],
    languages: ['bem', 'en'],
    currency: {
      code: 'ZMK',
      symbol: 'ZK',
      value: '0.00',
    },
    phoneCode: '260',
  },
  {
    id: 'ZW',
    name: 'Zimbabwe',
    type: 'C',
    timezone: 'Africa/Harare',
    timezones: ['Africa/Harare'],
    languages: ['en', 'nd', 'sn'],
    currency: {
      code: 'ZWL',
      symbol: '',
      value: '0.00',
    },
    phoneCode: '263',
  },
  {
    id: 'AX',
    name: 'Åland Islands',
    type: '',
    timezone: 'Europe/Mariehamn',
    timezones: ['Europe/Mariehamn'],
    languages: ['sv'],
    currency: {
      code: 'EUR',
      symbol: '€',
      value: '0.00',
    },
    phoneCode: '358',
  },
];
